name: air4dart
description: Implements the Airsonic API into pure dart for use in other applications.
version: 0.0.5
homepage: https://github.com/jacob-shuman/air4dart
author: Jacob Shuman <jacob.shuman7@gmail.com>

dependencies:
  crypto: ^2.0.6
  password_hash: ^2.0.0
  http: ^0.12.0+1

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
